run:
  allow-parallel-runners: true
  print-linter-name: true
  timeout: '5m0s'


output:
  print-issued-lines: true
  format: colored-line-number

issues:
  max-issues-per-linter: 50
  max-same-issues: 0  
  exclude:
    - "Error return value of .(.*MarkFlagRequired). is not checked"
    
linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Additional linters
    - nilerr
    # - nilnil
    - misspell