name: start-stop network test
on:
  pull_request:

permissions:
  contents: read
jobs:
  config:
    strategy:
      matrix:
        settings:
          # example:
          # - config_file: example_config.hcl
          #   propose_upgrade: true

          - config_file: config.hcl
          - config_file: config_clef.hcl
          - config_file: config_external_postgres.hcl
          - config_file: config_visor_mixed.hcl
            propose_upgrade: true

          # TODO: Needs to be fixed. Issue: https://github.com/vegaprotocol/vegacapsule/issues/291
          # - config_visor_only.hcl
    name: ${{ matrix.settings.config_file }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: actions/checkout@v3
      - name: Build binary
        env:
          GO111MODULE: on 
        run:
          go build -o vegacapsule .
      - name: Start nomad
        run: |
          export GOBIN=$(go env GOPATH)/bin
          ./vegacapsule nomad&
      - name: Wait for nomad
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:4646/ui/'
          responseCode: '200,302,307'
          timeout: 30000
          interval: 1000
      - name: Start the node
        run: |
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$GOBIN:$PATH

          ./vegacapsule install-bins --install-path $GOBIN
          ./vegacapsule network bootstrap --config-path ./net_confs/${{ matrix.settings.config_file }} ;
          sleep 5;
      - name: List nodes
        run: |
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$GOBIN:$PATH

          ./vegacapsule nodes ls;
      - name: Network propose upgrade
        if: ${{ matrix.settings.propose_upgrade }}
        run: |
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$GOBIN:$PATH

          ./vegacapsule nodes protocol-upgrade \
            --propose \
            --release-tag v0.58.0 \
            --template-path "net_confs/node_set_templates/default/visor_run.tmpl" \
            --height 5500 \
            --force

      - name: Network destroy
        run: |
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$GOBIN:$PATH

          ./vegacapsule network destroy;